@startuml
class Employee {
    + EmployeeID : int <<get>> <<set>>
    + FirstName : string? <<get>> <<set>>
    + LastName : string? <<get>> <<set>>
    + Email : string? <<get>> <<set>>
    + DateOfBirth : DateTime <<get>> <<set>>
    + Gender : string? <<get>> <<set>>
    + Address : string? <<get>> <<set>>
}
@enduml
